version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Replace with your actual environment variables
      - EVM_RPC=http://your-evm-rpc
      - PRIVATE_KEY=your-private-key
      - FLOW_ADDR=your-flow-address
      - IND_RPC=http://your-indexer-rpc
    volumes:
      - ./data:/data
    restart: unless-stopped
